version: "3.9"
    
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file: .env.local
        volumes: 
            - ./backend:/app/
        ports:
            - 127.0.0.1:5000:5000
        depends_on:
            - db
        command: gunicorn app:app -c ./config/gunicorn_config.py

    db:
        container_name: db
        image: postgis/postgis
        environment:
            POSTGRES_PASSWORD: postgres
        volumes:
            - ./hh_2po_4pgr.sql:/docker-entrypoint-initdb.d/init.sql
