FROM postgis/postgis

# install pgRouting osm2pgrouting

ENV PGROUTING_VERSION main
ENV PGROUTING_GIT_HASH 113aa3b60f60db20ecc00e28b2ef4ae7d5e76219

RUN apt update \
 && apt install -y \
        libboost-atomic1.74.0 \
        libboost-chrono1.74.0 \
        libboost-graph1.74.0 \
        libboost-date-time1.74.0 \
        libboost-program-options1.74.0 \
        libboost-system1.74.0 \
        libboost-thread1.74.0 \
 && apt install -y \
        build-essential \
        cmake \
        libboost-graph-dev \
        libpq-dev \
        postgresql-server-dev-${PG_MAJOR} \
        git \
       #  for osm2pgrouting
        expat \
        libpqxx-dev \
        libexpat1-dev \
        libboost-dev \
        libboost-program-options-dev \
 && mkdir -p /usr/src/pgrouting \
 && cd /usr/src/pgrouting \
 && git init \
 && git remote add origin https://github.com/pgRouting/pgrouting.git \
 && git fetch --depth 1 origin :${PGROUTING_GIT_HASH} \
 && git reset --hard FETCH_HEAD \
 && mkdir build \
 && cd build \
 && cmake .. \
 && make \
 && make install \
 && cd / \
 && rm -rf /usr/src/pgrouting \
#  for osm2pgrouting
 && mkdir -p /usr/src/osm2pgrouting \
 && cd /usr/src/osm2pgrouting \
 && git clone https://github.com/pgRouting/osm2pgrouting.git \
 && cd osm2pgrouting \
 && cmake -H. -Bbuild \
 && cd build/ \
 && make \
 && make install \
 && cd / \
 && rm -rf /usr/src/osm2pgrouting

 RUN rm /docker-entrypoint-initdb.d/10_postgis.sh
