version: "3"
    
services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        env_file: .env.local
        volumes: 
            - ./backend:/app/
        ports:
            - 127.0.0.1:5000:5000
        depends_on:
            - db
        command: gunicorn app:app -c ./config/gunicorn_config.py

    db:
        container_name: db
        build:
            context: ./database
            dockerfile: Dockerfile-db
        restart: always
        ports:
            - "5434:5432"
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        volumes:
            - ./database/init.sql.gz:/docker-entrypoint-initdb.d/init.sql.gz
